Repository kermitt2/grobid, pull requests merged in 2021-07, with the labels that each got.

#778 Training web services
  build.gradle
  doc/Grobid-service.md
  grobid-service/src/main/java/org/grobid/service/GrobidPaths.java
  grobid-service/src/main/java/org/grobid/service/GrobidRestService.java
  grobid-service/src/main/java/org/grobid/service/modules/GrobidServiceModule.java
  grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessTraining.java
Labels: enhancement

#761 override normalised date only when is empty
  build.gradle
  grobid-core/src/main/java/org/grobid/core/data/Date.java
  grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
  grobid-core/src/main/java/org/grobid/core/engines/DateParser.java
  grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
  grobid-core/src/main/java/org/grobid/core/features/FeatureFactory.java
  grobid-core/src/main/java/org/grobid/core/features/FeaturesVectorDate.java
  grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java
  grobid-core/src/main/java/org/grobid/core/utilities/crossref/CrossrefClient.java
  grobid-core/src/test/java/org/grobid/core/engines/DateParserIntegrationTest.java
  grobid-core/src/test/java/org/grobid/core/engines/DateParserTest.java
  grobid-core/src/test/java/org/grobid/core/test/TestDate.java
  grobid-core/src/test/java/org/grobid/core/utilities/ConsolidationTest.java
  grobid-core/src/test/java/org/grobid/core/utilities/GrobidTestUtils.java
  grobid-core/src/test/java/org/grobid/core/utilities/SentenceUtilitiesTest.java
Labels: bug

#791 Refine callout
  grobid-core/src/main/java/org/grobid/core/data/Figure.java
  grobid-core/src/main/java/org/grobid/core/data/Table.java
  grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
  grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
  grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
  grobid-core/src/main/java/org/grobid/core/engines/citations/AdditionalRegexTextSegmenter.java
  grobid-core/src/main/java/org/grobid/core/engines/citations/CalloutAnalyzer.java
  grobid-core/src/main/java/org/grobid/core/engines/citations/RegexReferenceSegmenter.java
  grobid-home/models/segmentation-BidLSTM_CRF_FEATURES/config.json
  grobid-home/models/segmentation-BidLSTM_CRF_FEATURES/model_weights.hdf5
  grobid-home/models/segmentation-BidLSTM_CRF_FEATURES/preprocessor.json
  grobid-trainer/src/main/java/org/grobid/trainer/evaluation/EndToEndEvaluation.java
Labels: bug, enhancement
